# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.18.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      PORT: ${{ secrets.PORT }}
      IMAGEKIT_PUBLIC_KEY: ${{ secrets.IMAGEKIT_PUBLIC_KEY }}
      IMAGEKIT_PRIVATE_KEY: ${{ secrets.IMAGEKIT_PRIVATE_KEY }}
      IMAGEKIT_URL_ENDPOINT: ${{ secrets.IMAGEKIT_URL_ENDPOINT }}  
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
      GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
      GOOGLE_REFRESH_TOKEN: ${{secrets.GOOGLE_REFRESH_TOKEN}}
      
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Dependencies
      run: npm ci

    # - name: Run Prisma Generate
    #   run: npm run prisma:generate

    # - name: Run Prisma Migrate
    #   run: npm run prisma:migrate

    - name: Build Application
      run: npm run build --if-present
    - name: Change Directory
      run: cd /home/becacps/actions-runner/_work/server-cyber-academy/server-cyber-academy/
      
    - name: restart with PM2
      run: pm2 restart 0
